# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7fedbfa9c467b10edd8431f5d0a5c4baa29b6804be887d22ad084293745494bc55b0581387c330e845ae29a2d2cf4d68cbe9b76999f32a41222f14e434bafe5

test:
  secret_key_base: 45395cd69df9a80c7c4e488a969219c119d828ed113dd69f05c072f4f0e8938c1eb11ef14866a9bc81614e4103c3a1457d325378edd847df77e1ea1a0aef6f8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
